source 'https://rubygems.org'
gem 'sinatra', '~> 4.2'      # >= 4.2 clears CVE-2024-21510 / CVE-2025-61921 (Rack 3)
gem 'rackup'                 # Rack 3 split rackup out of rack
gem 'puma'                   # Rack 3 server (thin 1.8 is Rack 2 only)
gem 'rack-session'           # Rack 3 extracted session middleware
gem 'faye-websocket'         # WS proxy, via rack.hijack under puma (no EventMachine)
gem 'eventmachine'           # faye dependency (not used as a reactor here)
gem 'erubi'                  # HTML-auto-escaping ERB (XSS protection)
gem 'omniauth', '~> 2.1'
gem 'omniauth-github'

group :test do
  gem 'rspec'
  gem 'rack-test'
end
